baseURL = "https://seojuncha.github.io/"
theme = "PaperMod"
enableRobotsTXT = true

defaultContentLanguage = "ko"

# [languages]
# [languages.en]
# disabled = false
# languageCode = "en"
# languageDirection = 'ltr'
# languageName = "English"
# title = "Seojun's Blog"
# weight = 1
# [languages.en.params.profileMode]
# enabled = false
# title = "Welcome! I am Seojun."
# subtitle = "💻 Freelancer Programmer\n\n🛠️ Low-Level | 🎨 Qt/QML | 🎥 Multimedia"

# [languages.en.params.homeInfoParams]
# title = "Welcome to my blog"
# Content = ""

# [languages.en.menus]
# [[languages.en.menus.main]]
# name = 'Search'
# pageRef = '/search'
# weight = 10
# [[languages.en.menus.main]]
# name = 'Blog'
# pageRef = '/posts'
# weight = 20
# [[languages.en.menus.main]]
# name = 'Archives'
# pageRef = '/archives'
# weight = 30
# [[languages.en.menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 40
# [[languages.en.menus.main]]
# name = 'Projects'
# pageRef = '/projects'
# weight = 25
# [[languages.en.menus.main]]
# name = 'From the transistor'
# pageRef = '/projects/from-the-transistor'
# parent = 'Projects'

# [languages.en]
# disabled = false
# languageCode = "ko"
# languageDirection = 'ltr'
# languageName = "한국어"
title = "Seojun Blog"
weight = 2
# [languages.ko.params.profileMode]
# enabled = false
# title = "반갑습니다! 프로그래머 차서준입니다."
# subtitle = "💻 프리랜서 프로그래머\n\n🛠️ 로우레벨 | 🎨 Qt/QML | 🎥 멀티미디어"
[params.homeInfoParams]
title = "Welcome to my blog"
Content = ""

[menus]
[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 10
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
[[menus.main]]
name = 'Archives'
pageRef = '/archives'
weight = 30
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40
[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 25
[[menus.main]]
name = 'From the transistor'
pageRef = '/projects/from-the-transistor'
parent = 'Projects'

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
filename = "sitemap.xml"

[markup]
[markup.highlight]
noClasses = true
tabWidth = 2
style = "xcode-dark"

[params]
env = "production"
cleanDestinationDir = true
defaultTheme = "light"
disableThemeToggle = true
comments = true
ShowPostNavLinks = true
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowToc = true
math = true
mathEngine = "katex"
# displayFullLangName = true

[params.utterances]
repo = "seojuncha/seojuncha.github.io"
issue-term = "pathname"
theme = "github-light"

[params.assets]
customCSS = ["css/extended/custom.css"]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[[params.socialIcons]]
name = "github"
url = "https://github.com/seojuncha"

# [[params.socialIcons]]
# name = "youtube"
# url = "https://www.youtube.com/@seojun-u-channel"

[[params.socialIcons]]
name = "email"
url = "mailto:sjcha36@gmail.com"

[[params.socialIcons]]
name = "rss"
url = "https://seojuncha.github.io/index.xml"

[caches]
[caches.images]
dir = ':cacheDir/images'
