baseURL = "https://seojuncha.github.io/"
theme = "PaperMod"
title = "Seojun's Personal Site"
enableRobotsTXT = true

defaultContentLanguage = "en"

[languages]
[languages.en]
disabled = false
languageCode = "en-US"
languageDirection = 'ltr'
languageName = "English"
weight = 1

[languages.ko]
disabled = false
languageCode = "ko-KR"
languageDirection = 'ltr'
languageName = "한국어"
weight = 2

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
filename = "sitemap.xml"

[markup]
[markup.highlight]
noClasses = true
tabWidth = 2
style = "xcode-dark"

[params]
env = "production"
cleanDestinationDir = true
defaultTheme = "light"
disableThemeToggle = true
comments = true
ShowPostNavLinks = true
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowToc = true
math = true
mathEngine = "katex"

[params.utterances]
repo = "seojuncha/seojuncha.github.io"
issue-term = "pathname"
theme = "github-light"

[params.assets]
customCSS = ["css/extended/custom.css"]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[params.homeInfoParams]
# Title = "Cha Seojun (차서준)"
# Title = "Seojun's Personal Site"
Content = "Exploring the intersection between hardware and software, diving deep into how technology operates at every level. From ARM Assembly and QEMU simulation to programming, system analysis, and beyond, I'll uncover how hardware and software interact seamlessly through hands-on examples and real-world projects. \n\n NOTE: I'm not a native English speaker, but I'll do my best to share what I know!"

[[params.socialIcons]]
name = "github"
url = "https://github.com/seojuncha"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@seojun-u-channel"

[[params.socialIcons]]
name = "email"
url = "mailto:sjcha36@gmail.com"

[[params.socialIcons]]
name = "rss"
url = "https://seojuncha.github.io/index.xml"

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30
